画角9分割による検出ブロックの追加
AkariGroup/scratch-vm pull request #6
Opened 2024-06-11 07:08 UTC by Wisteria720

カメラ画角を上下左右、真ん中で9分割て各エリアに物体が検出されたときにTrueを返すブロックを追加しました。

2024-06-17 01:22 UTC, kazyam53 requested changes
コメントの修正お願いします。

2024-06-17 01:22 UTC, kazyam53 commented on src/extensions/scratch3_akari_camera_simple/index.js
> +    }
```suggestion
        }
    return false
    }
```

falseのreturnがないため、認識されない時に何も結果が表示されません。

2024-06-17 07:53 UTC, Wisteria720 commented
@kazyam53 
ありがとうございます。修正しました

2024-07-12 03:36 UTC, kazyam53 approved these changes
LGTM

2024-07-16 06:23 UTC, merged